<?php
declare(strict_types=1);

namespace Iqteco\WaAdmin\Services;

use Symfony\Component\Process\Process;

final class NginxMapManager
{
    public function __construct(private readonly array $config, private readonly Logger $logger) {}

    /**
     * Регенерирует /etc/nginx/wa-instances.map из активных инстансов.
     * www-data не имеет write permission на /etc/nginx, поэтому пишем
     * в /run/wa-admin/wa-instances.map и устанавливаем через sudo helper
     * /usr/local/bin/wa-nginx-map-deploy (он делает install + nginx -s reload).
     */
    public function regenerate(): void
    {
        $instances = MongoClient::db($this->config)
            ->selectCollection('instances')
            ->find(
                ['state' => ['$ne' => 'deleted'], 'ipv6' => ['$ne' => null]],
                ['projection' => ['idInstance' => 1, 'ipv6' => 1]]
            )
            ->toArray();

        $lines = ['# auto-generated by NginxMapManager. DO NOT EDIT.'];
        foreach ($instances as $i) {
            if (empty($i['idInstance']) || empty($i['ipv6'])) continue;
            $lines[] = sprintf('%s [%s]:8080;', $i['idInstance'], $i['ipv6']);
        }
        $content = implode("\n", $lines) . "\n";

        $stageDir = '/run/wa-admin';
        @mkdir($stageDir, 0755, true);
        $stage = $stageDir . '/wa-instances.map';
        if (file_put_contents($stage, $content) === false) {
            throw new \RuntimeException("Cannot write {$stage}");
        }
        $this->reload();
        $this->logger->info('NginxMap regenerated', ['count' => count($lines) - 1]);
    }

    public function reload(): void
    {
        $proc = new Process(['/usr/bin/sudo', '/usr/local/bin/wa-nginx-map-deploy']);
        $proc->setWorkingDirectory('/tmp');
        $proc->setTimeout(15);
        $proc->run();
        if (!$proc->isSuccessful()) {
            $err = $proc->getErrorOutput() ?: $proc->getOutput();
            throw new \RuntimeException("nginx reload failed: {$err}");
        }
    }
}
