<?php
declare(strict_types=1);

namespace Iqteco\WaAdmin\Services;

use Symfony\Component\Process\Process;

final class NginxMapManager
{
    public function __construct(private readonly array $config, private readonly Logger $logger) {}

    /**
     * Регенерирует /etc/nginx/wa-instances.map из активных инстансов.
     * Затем reload nginx (через sudo allowlist).
     */
    public function regenerate(): void
    {
        $mapFile = $this->config['nginx']['map_file'];
        $instances = MongoClient::db($this->config)
            ->selectCollection('instances')
            ->find(
                ['state' => ['$ne' => 'deleted'], 'ipv6' => ['$ne' => null]],
                ['projection' => ['idInstance' => 1, 'ipv6' => 1]]
            )
            ->toArray();

        $lines = ['# auto-generated by NginxMapManager. DO NOT EDIT.'];
        foreach ($instances as $i) {
            if (empty($i['idInstance']) || empty($i['ipv6'])) continue;
            $lines[] = sprintf('%s [%s]:8080;', $i['idInstance'], $i['ipv6']);
        }
        $content = implode("\n", $lines) . "\n";

        $tmp = $mapFile . '.tmp';
        if (file_put_contents($tmp, $content) === false) {
            throw new \RuntimeException("Cannot write {$tmp}");
        }
        if (!@rename($tmp, $mapFile)) {
            throw new \RuntimeException("Cannot rename {$tmp} → {$mapFile}");
        }

        $this->reload();
        $this->logger->info('NginxMap regenerated', ['count' => count($lines) - 1]);
    }

    public function reload(): void
    {
        $proc = new Process(['/usr/bin/sudo', '/usr/sbin/nginx', '-s', 'reload']);
        $proc->setTimeout(10);
        $proc->run();
        if (!$proc->isSuccessful()) {
            $err = $proc->getErrorOutput() ?: $proc->getOutput();
            throw new \RuntimeException("nginx reload failed: {$err}");
        }
    }
}
